# Generated by Django 2.2.1 on 2019-08-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arxiv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
