# Generated by Django 2.2.1 on 2019-08-03 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arxiv', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxiv.Category')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxiv.Paper')),
            ],
        ),
    ]
