# Generated by Django 2.2.1 on 2019-08-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arxiv', '0003_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.TextField(default=''),
        ),
    ]
